apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-truta
spec:
  selector:
    matchLabels:
      run: nginx-truta
  replicas: 2
  template:
    metadata:
      labels:
        run: nginx-truta
    spec:
      containers:
      - name: nginx-truta
        image: nginx:1.14.2
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-nodeport
  labels:
    run: nginx-truta
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  selector:
    run: nginx-truta
