- name: Instalado os pacotes para comunicação segura do APT
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common
      - gnupg2
    state: present
    update_cache: yes

- name: Criando o arquivos /etc/apt/trusted.gpg.d/docker.gpg
  file:
    path: /etc/apt/trusted.gpg.d/docker.gpg
    state: touch

- name: Adicionado a chagne GPG do Docker
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    keyring: /etc/apt/trusted.gpg.d/docker.gpg

- name: Adicionando o repositório APT do Docker
  apt_repository:
    repo: deb https://download.docker.com/linux/ubuntu focal stable
    state: present

- name: Instalando o Docker CE e dependências
  apt:
    name:
      - containerd.io=1.2.13-2
      - docker-ce=5:19.03.11~3-0~ubuntu-focal
      - docker-ce-cli=5:19.03.11~3-0~ubuntu-focal
    state: present
    update_cache: yes

- name: Copiando o arquivo de configuração do Docker
  copy:
    src: template/daemon.json
    dest: /etc/docker/daemon.json

- name: Criando o diretório /etc/systemd/system/docker.service.d
  file:
    path:  /etc/systemd/system/docker.service.d
    state: directory

- name: Recarregando os deamons do Systemd
  systemd:
    daemon_reload: yes

- name: Reinciando o Docker
  systemd:
    name: docker
    state: started
    enabled: yes
