- name: Pré-requisitos
  hosts: all
  roles:
    - pre-reqs

- name: HAProxy
  hosts: haproxy
  roles:
    - haproxy

- name: etc
  hosts: etcds
  roles:
    - etcd

- name: Kubernetes - Instalação HA - Etcd Stacked
  hosts: control-plane,nodes
  roles:
    - pre-reqs
    - docker
    - kubernetes