- name: Pré-requisitos
  hosts: all
  roles:
    - pre-reqs

- name: HAProxy
  hosts: haproxy
  roles:
    - haproxy

- name: Kubernetes - Instalação HA - Stacked Etcd
  hosts: control-plane,nodes
  roles:
    - docker
    - kubernetes